### PR TITLE
🔒 Add `extcodesize` check to `SafeTransferLib`

### PR DESCRIPTION
**Pull request by MiloTruck**
## Description

Add an `extcodesize` check to all ERC20-related functions in `SafeTransferLib`, which ensures that the address at `token` has code if it does not return true.

## Checklist

Ensure you completed **all of the steps** below before submitting your pull request:

- [ ] Ran `forge snapshot`?
- [ ] Ran `npm run lint`?
- [ ] Ran `forge test`?

_Pull requests with an incomplete checklist will be thrown out._

### CODE REVIEW

**Comment by transmissions11** [comment]
LGTM — can remove the "/// @dev Note that none of the functions in this library check that a token has code at all! That responsibility is delegated to the caller." notice at the top too now right?

**Comment by MiloTruck** [comment]
> LGTM — can remove the "/// @dev Note that none of the functions in this library check that a token has code at all! That responsibility is delegated to the caller." notice at the top too now right?

You're right, I've removed the warning.

**Comment by MiloTruck** [comment]
I've added a short-circuit to avoid calling `extcodesize` for tokens that return true, as suggested by @Vectorized [here](https://x.com/milotruck/status/1846997750942147070).

**Comment by Moses-main** [comment]
Hi,

I'd like to contribute. Please assign any good first issue!

**Pull request merged**
